services:
  dbo:
    container_name: dbo-studio
    image: ghcr.io/dbo-studio/dbo/dbo:latest
    environment:
      APP_PORT: "9000"
      APP_ENV: "docker"
    volumes:
      - ./docker/dbo:/backend/data
    ports:
      - "9000:9000"