services:
  backend:
    container_name: dbo-studio-dev-api
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/back/
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
  frontend:
    container_name: dbo-studio-dev-frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    env_file: .env
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
  sample-pgsql:
    container_name: dbo-studio-sample-pgsql
    image: postgres:16.1
    ports:
      - "${DB_TEST_PORT-5432}:5432"
    volumes:
      - "./docker/data/pgsql:/var/lib/postgresql/data"
      - "./docs/sample_db/public.sql:/docker-entrypoint-initdb.d/public.sql"
    restart: always
    platform: "linux/amd64"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_TEST_DATABASE}
      POSTGRES_USER: ${DB_TEST_USERNAME}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
