services:
#  backend:
#    container_name: dbo-studio-dev-api
#    build:
#      context: ./backend
#      dockerfile: Dockerfile.dev
#    volumes:
#      - ./backend:/back/
#    environment:
#      APP_PORT: "8080"
#      APP_ENV: "docker"
#      DB_TEST_CONNECTION: "pgsql"
#      DB_TEST_HOST: "localhost"
#      DB_TEST_PORT: "5432"
#      DB_TEST_DATABASE: "default"
#      DB_TEST_USERNAME: "default"
#      DB_TEST_PASSWORD: "secret"
#    ports:
#      - "8080:8080"
  frontend:
    container_name: dbo-studio-dev-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      NEXT_PUBLIC_SERVER_URL: "http://localhost:8080/api"
    ports:
      - "3000:3000"
  sample-pgsql:
    container_name: dbo-studio-sample-pgsql
    image: postgres:16.1
    ports:
      - "${DB_TEST_PORT-5432}:5432"
    volumes:
      - "./docker/data/pgsql:/var/lib/postgresql/data"
      - "./docs/sample_db/public.sql:/docker-entrypoint-initdb.d/public.sql"
    restart: always
    platform: "linux/amd64"
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret