name: Backend Test

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - main
      - "release/*.*.*"
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"

jobs:
  go-static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          check-latest: true
          cache: true
      - name: Verify go.mod is tidy
        working-directory: ./backend
        run: |
          go mod tidy -go=1.22
          git diff --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
          args: --verbose --timeout=3m
          skip-cache: true