name: Docker Build and Push

on:
  push:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read version from file
      id: get_version
      run: |
        VERSION=$(cat version.txt)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}/dbo
        docker build -t $IMAGE_NAME:${{ env.VERSION }} .
        docker tag $IMAGE_NAME:${{ env.VERSION }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ env.VERSION }}
        docker push $IMAGE_NAME:latest