name: Build and Push Docker Image

on:
  push:
    branches: [ build_flow ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.GITHUB_REGISTRY }}/$GITHUB_REPOSITORY:${{ github.sha }}  # Pushes with tag based on commit SHA
          context: .  # Build context is the current directory