name: Tests

on:
  push:
    branches: [master, release, dev]

  pull_request:
    branches: [master, release, dev]
    paths: ["go.mod", "go.sum", "**.go"]

jobs:
  go-static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
          cache: true
      - name: Verify go.mod is tidy
        working-directory: ./backend
        run: |
          go mod tidy -go=1.23
          git diff --exit-code
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./backend
          version: v1.61.0
          args: --verbose --timeout=3m
          skip-cache: true

  front-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci fronted/src

  front-test:
    runs-on: ubuntu-latest
    steps:
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
     
      - name: install frontend dependencies
        run: npm install --force
        working-directory: ./frontend
      
      - name: run tests
        run: npm run test
        working-directory: ./frontend